version: "3.8"

services:
    app:
        build: ./
        depends_on:
            - db
        ports:
            - 800:80
        volumes:
            - ./:/var/www/html
    db:
        container_name: 'postgres'
        image: postgres
        restart: always
        ports:
            - 6543:5432
        volumes:
            - ultrashop:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}

volumes:
    ultrashop:
